// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module LZC(	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:221:7
  input  [4:0] io_in,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:222:14
  output [2:0] io_out	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:222:14
);

  assign io_out =
    io_in[4] ? 3'h0 : io_in[3] ? 3'h1 : io_in[2] ? 3'h2 : io_in[1] ? 3'h3 : 3'h4;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:221:7, :227:35, src/main/scala/chisel3/util/Mux.scala:50:70
endmodule

module FPAdder_6_10(	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
  input        clock,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
               reset,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
  input  [5:0] io_in_a,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:232:14
               io_in_b,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:232:14
  input        io_valid_in,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:232:14
  output [5:0] io_out,	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:232:14
  output       io_valid_out	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:232:14
);

  wire [2:0]  _lzc_io_out;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:280:19
  wire [3:0]  normFracA = {1'h1, io_in_a[2:0]};	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:246:22, :253:22
  wire [3:0]  normFracB = {1'h1, io_in_b[2:0]};	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:250:22, :253:22, :254:22
  wire        expAGtB = io_in_a[4:3] > io_in_b[4:3];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:245:21, :249:21, :258:22
  wire [1:0]  _expDiff_T_4 =
    expAGtB ? io_in_a[4:3] - io_in_b[4:3] : io_in_b[4:3] - io_in_a[4:3];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:245:21, :249:21, :258:22, :259:{17,32,45}
  wire [3:0]  _GEN = {2'h0, _expDiff_T_4};	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :259:17, :267:31
  wire [2:0]  _GEN_0 = expAGtB ? io_in_a[2:0] : io_in_b[2:0];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:246:22, :250:22, :258:22, :265:17, :266:18, :270:18
  wire [3:0]  _GEN_1 = expAGtB ? normFracB >> _GEN : normFracA >> _GEN;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:253:22, :254:22, :258:22, :265:17, :267:{18,31}, :271:{18,31}
  wire [1:0]  expOut = expAGtB ? io_in_a[4:3] : io_in_b[4:3];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:245:21, :249:21, :258:22, :265:17, :268:12, :272:12
  wire [4:0]  _fracSum_T = {2'h1, _GEN_0} + {1'h0, _GEN_1};	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :265:17, :266:18, :267:18, :270:18, :271:18, :276:30, :291:37
  wire        _GEN_2 = ~(_fracSum_T[4]) & _fracSum_T[3];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30, :277:25, :291:{37,45,55}
  wire [11:0] _shiftedFrac_T_1 = {7'h0, _fracSum_T} << _lzc_io_out;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30, :280:19, :297:28
  wire [2:0]  shiftedFrac =
    _fracSum_T[4] ? _fracSum_T[3:1] : _GEN_2 ? _fracSum_T[2:0] : _shiftedFrac_T_1[2:0];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30, :277:25, :287:18, :289:17, :291:{45,76}, :293:17, :297:{17,28}
  wire [1:0]  newExp =
    _fracSum_T[4]
      ? expOut + 2'h1
      : _GEN_2
          ? expOut
          : {1'h0, expOut} >= _lzc_io_out ? expOut - _lzc_io_out[1:0] : 2'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :265:17, :268:12, :272:12, :276:30, :277:25, :280:19, :287:18, :290:{12,22}, :291:{37,45,76}, :294:12, :298:{12,18,26,46}
  wire [5:0]  result = {1'h0, newExp, shiftedFrac};	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:287:18, :289:17, :290:12, :291:{37,76}, :304:19
  reg         sr_valid_0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_1;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_2;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_3;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_4;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_5;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_6;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_7;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_8;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg         sr_valid_9;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
  reg  [5:0]  sr_data_0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_1;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_2;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_3;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_4;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_5;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_6;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_7;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_8;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  reg  [5:0]  sr_data_9;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  `ifndef SYNTHESIS	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11
    always @(posedge clock) begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11
      automatic logic _GEN_3 = io_valid_in & ~(_fracSum_T[4]);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30, :277:25, :291:37, :345:20
      automatic logic _GEN_4 = (`PRINTF_COND_) & io_valid_in & ~reset;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11
      if (_GEN_4) begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :344:11
        $fwrite(32'h80000002, "[STEP 1: Extract Fields]\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11
        $fwrite(32'h80000002, "  A = %b => signA: %b | expA: %b | fracA: %b\n", io_in_a,
                io_in_a[5], io_in_a[4:3], io_in_a[2:0]);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:244:22, :245:21, :246:22, :327:11, :328:11
        $fwrite(32'h80000002, "  B = %b => signB: %b | expB: %b | fracB: %b\n", io_in_b,
                io_in_b[5], io_in_b[4:3], io_in_b[2:0]);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:248:22, :249:21, :250:22, :327:11, :329:11
        $fwrite(32'h80000002, "[STEP 2: Compare Exponents]\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :331:11
        $fwrite(32'h80000002, "  expA: %d, expB: %d\n", io_in_a[4:3], io_in_b[4:3]);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:245:21, :249:21, :327:11, :332:11
        $fwrite(32'h80000002, "  expDiff: %d => expAGtB: %b\n", {1'h0, _expDiff_T_4},
                expAGtB);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:258:22, :259:{11,17}, :291:37, :327:11, :333:11
        $fwrite(32'h80000002, "[STEP 3: Align Mantissas]\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :335:11
        $fwrite(32'h80000002, "  normFracA (with hidden 1): %b\n", normFracA);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:253:22, :327:11, :336:11
        $fwrite(32'h80000002, "  normFracB (with hidden 1): %b\n", normFracB);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:254:22, :327:11, :337:11
        $fwrite(32'h80000002, "  alignedLarge: %b | alignedSmall: %b\n", {2'h1, _GEN_0},
                {1'h0, _GEN_1});	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :265:17, :266:18, :267:18, :270:18, :271:18, :291:37, :327:11, :338:11
        $fwrite(32'h80000002, "  selectedExpOut: %d\n", expOut);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:265:17, :268:12, :272:12, :327:11, :339:11
        $fwrite(32'h80000002, "[STEP 4: Add Aligned Mantissas]\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :341:11
        $fwrite(32'h80000002, "  sum: %b (carryOut = %b)\n", _fracSum_T, _fracSum_T[4]);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30, :277:25, :327:11, :342:11
        $fwrite(32'h80000002, "[STEP 5: Normalize Result]\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :344:11
      end
      if ((`PRINTF_COND_) & io_valid_in & _fracSum_T[4] & ~reset)	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30, :277:25, :327:11, :346:13
        $fwrite(32'h80000002, "  CarryOut = 1 => shift right by 1\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :346:13
      if ((`PRINTF_COND_) & _GEN_3 & _GEN_2 & ~reset)	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:45, :327:11, :345:20, :348:13
        $fwrite(32'h80000002, "  Already normalized => no shift needed\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :348:13
      if ((`PRINTF_COND_) & _GEN_3 & ~_GEN_2 & ~reset)	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:45, :327:11, :345:20, :347:78, :350:13
        $fwrite(32'h80000002, "  No CarryOut => LZC = %d | shift left\n", _lzc_io_out);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:280:19, :327:11, :350:13
      if (_GEN_4) begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :357:11
        $fwrite(32'h80000002, "  normFrac: %b | normExp: %d\n", shiftedFrac, newExp);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:287:18, :289:17, :290:12, :291:76, :327:11, :352:11
        $fwrite(32'h80000002, "[STEP 6: Final Result Reassembly]\n");	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:327:11, :354:11
        $fwrite(32'h80000002, "  Final result = %b\n", result);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:304:19, :327:11, :355:11
        $fwrite(32'h80000002,
                "[Cycle Info] bw = %d | pd = %d => valid_out: %b | output: %b\n", 3'h6,
                4'hA, sr_valid_9, sr_data_9);	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25, :308:20, :327:11, :357:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
    if (reset) begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      sr_valid_0 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_1 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_2 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_3 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_4 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_5 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_6 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_7 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_8 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
      sr_valid_9 <= 1'h0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:291:37, :307:25
    end
    else begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      sr_valid_0 <= io_valid_in;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_1 <= sr_valid_0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_2 <= sr_valid_1;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_3 <= sr_valid_2;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_4 <= sr_valid_3;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_5 <= sr_valid_4;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_6 <= sr_valid_5;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_7 <= sr_valid_6;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_8 <= sr_valid_7;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
      sr_valid_9 <= sr_valid_8;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:307:25
    end
    if (io_valid_in)	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:232:14
      sr_data_0 <= result;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:304:19, :308:20
    sr_data_1 <= sr_data_0;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_2 <= sr_data_1;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_3 <= sr_data_2;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_4 <= sr_data_3;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_5 <= sr_data_4;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_6 <= sr_data_5;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_7 <= sr_data_6;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_8 <= sr_data_7;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
    sr_data_9 <= sr_data_8;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:308:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      `FIRRTL_BEFORE_INITIAL	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      automatic logic [31:0] _RANDOM[0:2];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
        `INIT_RANDOM_PROLOG_	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
        end	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
        sr_valid_0 = _RANDOM[2'h0][0];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_1 = _RANDOM[2'h0][1];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_2 = _RANDOM[2'h0][2];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_3 = _RANDOM[2'h0][3];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_4 = _RANDOM[2'h0][4];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_5 = _RANDOM[2'h0][5];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_6 = _RANDOM[2'h0][6];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_7 = _RANDOM[2'h0][7];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_8 = _RANDOM[2'h0][8];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_valid_9 = _RANDOM[2'h0][9];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
        sr_data_0 = _RANDOM[2'h0][15:10];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25, :308:20
        sr_data_1 = _RANDOM[2'h0][21:16];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25, :308:20
        sr_data_2 = _RANDOM[2'h0][27:22];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25, :308:20
        sr_data_3 = {_RANDOM[2'h0][31:28], _RANDOM[2'h1][1:0]};	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25, :308:20
        sr_data_4 = _RANDOM[2'h1][7:2];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
        sr_data_5 = _RANDOM[2'h1][13:8];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
        sr_data_6 = _RANDOM[2'h1][19:14];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
        sr_data_7 = _RANDOM[2'h1][25:20];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
        sr_data_8 = _RANDOM[2'h1][31:26];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
        sr_data_9 = _RANDOM[2'h2][5:0];	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
      `FIRRTL_AFTER_INITIAL	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  LZC lzc (	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:280:19
    .io_in  (_fracSum_T),	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:276:30
    .io_out (_lzc_io_out)
  );
  assign io_out = sr_data_9;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :308:20
  assign io_valid_out = sr_valid_9;	// C:\\Users\\josea\\IdeaProjects\\AdderNet-Neural-Network\\src\\main\\scala\\Fundamental_IC.scala:230:7, :307:25
endmodule

